# Generated by Django 5.1.15 on 2026-05-06 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Preferences or anything to remember about this customer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='tailor, seamstress, cutter, etc.', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fabric_type', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('stock_meters', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('price_per_meter', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bust', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('waist', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('hips', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('shoulder_width', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sleeve_length', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('inseam', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_length', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('extra_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garment_type', models.CharField(help_text='dress, suit, trousers, shirt, etc.', max_length=50)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('design_notes', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('rush', 'Rush')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_production', 'In Production'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('materials', models.ManyToManyField(blank=True, related_name='garments', to='shop.material')),
                ('measurement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garment', to='shop.measurement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('received', 'Received'), ('confirmed', 'Confirmed'), ('in_production', 'In Production'), ('ready_for_delivery', 'Ready for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='received', max_length=30)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shop.customer')),
            ],
            options={
                'ordering': ['-order_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('method', models.CharField(choices=[('pickup', 'Pickup at Shop'), ('courier', 'Courier'), ('in_person', 'In-Person Delivery')], default='pickup', max_length=30)),
                ('final_observations', models.TextField(blank=True)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='shop.order')),
            ],
            options={
                'verbose_name_plural': 'Deliveries',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('garment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='shop.garment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
            ],
        ),
        migrations.CreateModel(
            name='WorkTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('order_received', 'Order Received'), ('design_confirmed', 'Design Confirmed'), ('cutting', 'Cutting'), ('sewing', 'Sewing'), ('finishing', 'Finishing'), ('quality_check', 'Quality Check'), ('ready_for_delivery', 'Ready for Delivery'), ('rework', 'Rework')], default='order_received', max_length=30)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('rush', 'Rush')], default='normal', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='shop.employee')),
                ('garment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='shop.garment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(blank=True, choices=[('order_received', 'Order Received'), ('design_confirmed', 'Design Confirmed'), ('cutting', 'Cutting'), ('sewing', 'Sewing'), ('finishing', 'Finishing'), ('quality_check', 'Quality Check'), ('ready_for_delivery', 'Ready for Delivery'), ('rework', 'Rework')], max_length=30)),
                ('to_stage', models.CharField(choices=[('order_received', 'Order Received'), ('design_confirmed', 'Design Confirmed'), ('cutting', 'Cutting'), ('sewing', 'Sewing'), ('finishing', 'Finishing'), ('quality_check', 'Quality Check'), ('ready_for_delivery', 'Ready for Delivery'), ('rework', 'Rework')], max_length=30)),
                ('comments', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_logs', to='shop.employee')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='shop.workticket')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
